### ISSUE TITLE
Game over pop up stayed forever 

### ISSUE THREAD

**Issue by DaniSpringer** [lichess-org/lichobile#1698] opened 2021-05-25 19:12 UTC
No matter where I tapped it didn’t go away for the whole game, until I quit the app. 

![CCC06FB6-B947-46F6-9718-30D8B04A82E0](https://user-images.githubusercontent.com/19246409/119555198-968e7180-bd6b-11eb-85a1-329c5b7ec2cb.png)

**Comment by cpsnell** [comment] 2021-05-25 23:55
I experienced the same issue… happens after opponent gives a rematch after a game and you click join….

**Comment by cpsnell** [comment] 2021-05-25 23:55
![86984C0D-961B-4AA2-B6BA-3476D7674031](https://user-images.githubusercontent.com/3050799/119582783-34e1fd80-bd93-11eb-9497-e88481157f7b.png)

**Comment by aimorris** [comment] 2021-05-31 23:07
Duplicate of #1481

**Closed** 2022-11-28 04:34 UTC
