### ISSUE TITLE
IOS App Profile Friends List Empty

### ISSUE THREAD

**Issue by SupremeDragon77** [lichess-org/lichobile#2502] opened 2024-09-16 16:21 UTC
### What happened?

When you go to your profile and tap on “Friends” the list is empty. The list populates on the web so I know that there is a bug in the mobile app. I also tried accessing the list with a friend online, but still nothing populated. This ticket is not referring to the “# friends online” list. That list works just fine. This ticket is referring to the friends list within the profile. 

### How can we reproduce the bug?

1. Open the IOS App
2. Click on the menu icon (Hamburger icon) 
3. Click on username
4. Click profile
5. Click Friends
6. The list is completely empty. I attached two images in the screenshots section. The empty list image is from the app. The other image shows that the web version does show the friends list. 

### Expected behavior

I expect to see a full list of my friends on the page. 

### Device

iPhone 15 Pro

### Operating system

iOS 17.6.1

### App version

v8.0.0

### Screenshots

![IMG_2474](https://github.com/user-attachments/assets/4f46a70d-0b23-4ded-bd0c-fd2f29d3a5fb)
![IMG_2473](https://github.com/user-attachments/assets/4debae65-c7a7-41ba-81d6-be0d7827f8ba)

### Additional context

I am experiencing this issue and so is one of my friends. I also checked Reddit and found some other reports of this same issue. Thanks!

**Comment by jas14** [comment] 2024-09-16 16:38
Duplicate of #2460

**Closed by jas14** 2024-09-16 16:38 UTC
Labels: bug
