### ISSUE TITLE
Stockfish 1 takes move with my pieces

### ISSUE THREAD

**Issue by mschiener** [lichess-org/lichobile#1684] opened 2021-05-14 18:01 UTC
## Symptom

When I castle, Stockfish moves a piece of mine. Doesn't matter if I castle kingside right away or later on. Even if I just develop my pieces and castle queenside later, Stockfish instantly moves a piece of mine. This doesn't happen if I don't castle at all.
Sometimes nothing happens - Stockfish doesn't move any pieces and the gameplay "freezes" (but I can still undo the moves and operate the app normally).

In both situations I cannot move on with the gameplay, neither can Stockfish.

I started it as an offline game.

Quick demonstration:
https://youtu.be/pKWoNM53lQs

**Update:
Seems like this is the case for every game I play, even after restarting the phone.**

## PGN

```[Event "Casual Game"]
[Site "https://lichess.org"]
[Date "14.5.2021, 18:55:19"]
[White "MathematicalPi"]
[Black "Stockfish Stufe 1"]
[Result "*"]
[PlyCount "10"]
[FEN "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"]
[Variant "From Position"]
[Termination "?"]

1. d4 d6 2. c4 e5 3. Nf3 f6 4. e4 Nd7 5. Bd3 c5 *
```
### Lichess
Version 7.11.0
### Phone
Device Name: Huawei P30 Pro
Model: VOG-L29
Build-Number: 11.0.0.147(C431E8R2P3) GPU Turbo
EMUI-Version: 11.0.0
Android Version: 10
Processor: Huawei Kirin 980
RAM: 8,0 GB

**Comment by jas14** [comment] 2021-05-14 18:14
Thanks for the very detailed report. This appears to be a duplicate of #1637 - do you mind merging it into that one?

**Comment by mschiener** [comment] 2021-05-14 20:01
Oh sorry, I haven't seen this one, but it's definitely a duplicate. So I'm totally fine merging them ☺️

I also just tried different stockfish levels. The Bug seems to be independent of the level.

**Comment by mschiener** [comment] 2021-05-14 21:26
Another update:

Now I cloned my lichess instance on the phone. I wanted to preserve the current state of the app data and cache but to start like from a clean install.

The cloned instance just works fine - I'm able to castle as normal without any bugs. So resetting the app data/cache should work. Nevertheless I'll keep my app state for now just in case it's of any interest for you.

**Comment by jas14** [comment] 2022-09-18 21:07
As noted, duplicate of #1637

**Closed by jas14** 2022-09-18 21:07 UTC
