### ISSUE TITLE
There is no option to choose puzzle pattern on mobile app

### ISSUE THREAD

**Issue by mzylowski** [lichess-org/lichobile#2309] opened 2023-02-13 21:59 UTC
On lichess.org there is an option to train only puzzles from given group (pattern) but there is no option to chose group from lichess android app. Also app forces to be used instead of page in browser, so that makes puzzles impossible to play on phone (when I want to try some choosen taticts etc)

**Comment by jas14** [comment] 2023-04-06 23:54
Duplicate of #2186

**Closed by jas14** 2023-04-06 23:54 UTC
Labels: bug
