### ISSUE TITLE
Eval in analysis gives wrong board when not in the lines tab

### ISSUE THREAD

**Issue by MarcCowan** [lichess-org/lichobile#2055] opened 2022-03-08 21:40 UTC
When I'm in the analysis board, with Stockfish on (in the app), if I have the opening explorer (book icon) or the notation tab (text icon) open, instead of the lines tab, the eval on the top left of the right panel is wrong (for example it was giving -8.0 for a mainline caro-kann, then +7.1 after playing the top engine move, at reasonable depth). When you go into the lines tab, the display format for the right panel changes so it doesn't appear their and gives the correct eval, but the issue returns if you go back to the opening explorer or notation tab. Quite annoying if you're trying to check your opening play with the opening explorer.

**Comment by veloce** [comment] 2022-03-09 19:21
Duplicate of #2045

**Closed by veloce** 2022-03-09 19:21 UTC
