### ISSUE TITLE
When opening the application, an error message pops up. I request to block this pop-up

### ISSUE THREAD

**Issue by Hgnim** [lichess-org/lichobile#2530] opened 2024-11-28 10:41 UTC
As shown in the picture, this error message appears every time I open the software. I have updated the webview to the latest version, but it is not working. Request to block this pop-up window.
![](https://github.com/user-attachments/assets/77a6e502-fb61-4b8a-ac58-ce1a40f65870)

**Comment by jas14** [comment] 2024-12-01 04:18
Duplicate of #1448

**Closed by jas14** 2024-12-01 04:18 UTC
