### ISSUE TITLE
Please add practice to app

### ISSUE THREAD

**Issue by akarimia** [lichess-org/lichobile#1559] opened 2021-02-16 18:52 UTC
Hi
In lichess.org there is a learn menu that is include basics, practice, pazzels and study parts but in lichess mobile app I can't find basics and practice, please add them to app.
Best wishes.

**Comment by arieltz23** [comment] 2021-04-30 12:12
I would also love it if the practice menu at https://lichess.org/practice would be integrated into the app, I'm sure many other users would find it super helpful! :)

**Comment by shah-xad** [comment] 2022-02-18 22:00
I also want this.

**Comment by jas14** [comment] 2022-12-31 20:55
Duplicate of #759

**Closed by jas14** 2022-12-31 20:55 UTC
