### ISSUE TITLE
Puzzle check bug

### ISSUE THREAD

**Issue by Salmon1900** [lichess-org/lichobile#1511] opened 2021-01-18 09:45 UTC
When you start a puzzle when the openent has you in check position - your king is not highlighted and it can go un-noticed until you try move a piece
Slightly annoying cause sometimes you waste time looking for somthing else
Thanks, Idan

**Comment by kotem13** [comment] 2021-03-21 15:49
Example puzzle:
Dmgd3/819735359

Doesn't happen in the browser simulator, but I was able to reproduce it in my android:
Xiaomi Mi 8, Android 10
Lichess 7.9.0


<img alt="puzzle_check_highlight_missing" src="https://user-images.githubusercontent.com/42043575/111911184-bf8d4000-8a64-11eb-9eb8-f54c6ab0e0f0.jpeg" width="300px">

**Comment by jas14** [comment] 2021-03-21 17:52
Duplicate of #1597 (or technically the other way around)... In either case, fix has been merged

**Comment by jas14** [comment] 2022-12-31 20:58
Fixed in #1608 and released in v7.10.0!

**Closed by jas14** 2022-12-31 20:58 UTC
