### ISSUE TITLE
Repeating puzzles

### ISSUE THREAD

**Issue by tbena** [lichess-org/lichobile#1359] opened 2020-08-30 22:52 UTC
Starting today I keep getting the same puzzle when pressing the refresh button on the app. Also, my puzzle rating does not change after solving puzzles on the app, which is the expected behavior when solving puzzles you already saw, but I can't manage to get new ones.

**Comment by rbreitenstein00** [comment] 2020-09-18 15:26
After the app version 7.3.0 the counter of the rating has a bug! Deinstall the app and install 7.3.0

**Comment by jas14** [comment] 2022-12-31 21:30
Duplicate of #1308

**Closed by jas14** 2022-12-31 21:30 UTC
