### ISSUE TITLE
Studies are not accessable 

### ISSUE THREAD

**Issue by gustavdalemo** [lichess-org/lichobile#2511] opened 2024-09-27 08:45 UTC
### What happened?

When selecting any study, it just opens up an empty board and a loading animation, but the loading never resolves.

### How can we reproduce the bug?

1. Go to menu
2. Select "studies" ("studier" in Swedish)
3. Select any study.
4. You've arrived at the bug 🪲

### Expected behavior

I expect the study to load.

### Device

Xiaomi mi 10

### Operating system

Android 13 (Xiaomi Hyper Os)

### App version

V8.0.0

### Screenshots

![Screenshot_2024-09-27-10-41-08-591_org lichess mobileapp](https://github.com/user-attachments/assets/f6d2625d-385f-45a0-8521-242bce2a2f55)

### Additional context

It has been going on for some days now.

**Comment by Ankanahadoww** [comment] 2024-09-28 04:37
Same

**Comment by jas14** [comment] 2024-10-08 05:07
Duplicate of #2509

**Closed by jas14** 2024-10-08 05:07 UTC
Labels: bug
