### ISSUE TITLE
Offline puzzle solving does not fully update rating after going online.

### ISSUE THREAD

**Issue by kgardas** [lichess-org/lichobile#1594] opened 2021-03-12 14:57 UTC
**Describe the bug**
When I solve full batch of 50 puzless offline on my Androind phone and then go online,
my profile report then claims I've solved just a few puzzles -- like offline puzzle would not save all results or not upload all results.

**To Reproduce**
1. refresh to 50 puzzles
2. go offline
3. solve some puzzles (at least a few)
4. go on-line and refresh puzzles
5. verify in online (web) profile your rating is updated accordingly -- verify number of loses and wins.

**Expected behavior**
The number of wins and loses needs to show real number of loses/wins I've done in puzzles even in offline mode.
**Smartphone (please complete the following information):**
 - Device: Nokia 5
 - OS: Android 9
 - stock browser
 - Version 7.8.1 (text in small font in Menu -> Settings -- bottom of screen)

**Comment by jas14** [comment] 2022-10-26 15:36
Thank you for the detailed report. Closing as a duplicate of #1972, which is newer but happens to have more upvotes for interest tracking.

**Closed by jas14** 2022-10-26 15:36 UTC
