### ISSUE TITLE
Eval box shows ex. 5th-best move eval, not top move eval

### ISSUE THREAD

**Issue by jacksonthall22** [lichess-org/lichobile#2051] opened 2022-03-05 16:37 UTC
**Describe the bug**
On an analysis board, when not on the engine tab and "Multiple lines" is set to something more than 1, the eval shown in the top left of the tab view is the eval of the worst top line. For example, if multiple lines is 5, the eval of the 5th line is shown. This is true no matter whose side it is to move.

**To Reproduce**
1. Open analysis board on a completed game
2. Make sure "Toggle engine evaluation" is on and "Multiple lines" is > 1 (ex. 5 for maximum effect). Call this *n*
3. Navigate to a position where the top move eval and the *n*th move eval is different 
4. Swipe to a tab other than the engine tab
5. Check the eval number in the top left and notice it matches the eval of the *n*th line, not the top line

**Expected behavior**
The eval box should show the eval of the top line: maximizing for white and minimizing for black. Currently it is minimized for white and maximized for black.

**Screenshots**
Note the eval on the top left of the tab view. It is +5.4 because there are fewer than 5 moves that save the black queen:
![Screenshot_20220305-110321](https://user-images.githubusercontent.com/25040219/156891968-9e44f332-25f3-4c18-bdee-4c46ac0c1efd.png)

This matches the eval of the 5th move because multiple lines = 5:
![Screenshot_20220305-110324](https://user-images.githubusercontent.com/25040219/156891988-4e981796-caf1-4b7b-add2-2091178388d6.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3 XL
 - OS: Android version: 12, Android security update: October 5, 2021
 - Browser: Android app (v7.15.0)

**Comment by veloce** [comment] 2022-03-07 10:00
Thanks for the report but it's a duplicate of #2045

**Closed by veloce** 2022-03-07 10:00 UTC
Labels: bug
