### ISSUE TITLE
Major big in puzzle section on lichess mobile app 

### ISSUE THREAD

**Issue by djnevilmorgan** [lichess-org/lichobile#1665] opened 2021-04-30 03:06 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**
This is about A major bug I found on the lichess  mobile version .In the puzzle section of the app there are plenty of puzzle contains checkmate attack on the king  by undefended opponent pieces .Game is simply thinks that king cant cut pieces that attack him even when there is no defend against attacking piece ..almost all puzzle have this error .please consider about this bug .this makes the game soo unreliable 
Huawei Y7 pro
Android 7
Lichess mobile app latest version

**Comment by jas14** [comment] 2021-04-30 12:44
Can you provide a link to a puzzle where this happens, and the sequence of moves you expect to solve the puzzle?

**Comment by cyrille-artho** [comment] 2021-11-01 16:09
Perhaps this is a puzzle where the attacker simply improves their position without an actual checkmate?
This is not a bug then, although I agree that such puzzles are rather anticlimactic.

**Comment by jas14** [comment] 2022-10-25 13:16
Can't reproduce. Closing until more information is provided.

**Closed by jas14** 2022-10-25 13:16 UTC
