### ISSUE TITLE
Impossible to find Opponent

### ISSUE THREAD

**Issue by raivojutans** [lichess-org/lichobile#1936] opened 2021-12-02 19:15 UTC
Searching opponents takes took long time and move confirm as well.
![610F2FE4-701A-42E4-9A9C-9155FE76CE6D](https://user-images.githubusercontent.com/29740971/144487947-473a9c70-202c-4513-a3b2-ad822efabc7a.png)
![74B45066-FCD0-4E4C-8400-F1DF1B247AC5](https://user-images.githubusercontent.com/29740971/144487955-395023b2-bbce-4636-b93d-2efeccb57bf1.png)
![388EA227-44D2-4BCC-A21B-35308C6494A4](https://user-images.githubusercontent.com/29740971/144487958-fddb0614-8194-419d-8fcb-9e7737ff63cd.png)

**Comment by raivojutans** [comment] 2021-12-02 19:22
I can solve it by deleting App or restarting iPhone. Lichess was deleted a lot of times and re-installed.

**Comment by jas14** [comment] 2022-12-08 23:31
Duplicate of #1898.

**Closed by jas14** 2022-12-08 23:31 UTC
