### ISSUE TITLE
Opponent's clock timing out resulted in my loss

### ISSUE THREAD

**Issue by batconjurer** [lichess-org/lichobile#2328] opened 2023-03-11 14:34 UTC
**Describe the bug**
After I granted an opponent a take back, their clock continued to count down. I did not receive any new moves and the app clearly made it clear it was their turn. Then their clock ran out. The app stated my clock had run out and gave me a loss. It also stated that letting that happen could result in a temporary ban.

After going back to review the game, it finally showed the move my opponent had played and added their clock time back. 

**To Reproduce**
No idea, but it was certainly infuriating.

**Expected behavior**
I would have been awarded the win.

**Comment by jas14** [comment] 2023-03-11 16:32
Thanks for the report, batconjurer. This is unfortunately probably a symptom of a larger bug we've been seeing for a while where moves go out of sync. Unfortunately, we haven't made any progress on tracking it down. I'm going to close this as a duplicate of #1929, among others:

- #2120
- #1151
- #1916

**Closed by jas14** 2023-03-11 16:32 UTC
Labels: bug
