### ISSUE TITLE
Friends page

### ISSUE THREAD

**Issue by devapp2012** [lichess-org/lichobile#2491] opened 2024-07-18 10:36 UTC
### What happened?

I cannot see anything on my “friends” page on my iphone app. Followers, following whatever. It just gives a black blank screen when I click on Friends.. iphone 14… I have tried uninstalling and installing the app and restarting my phone a couple of times already.

### How can we reproduce the bug?

Go to Profile and then Friends

### Expected behavior

As earlier, I want to see my friends, followers, following on this page

### Device

iphone 14

### Operating system

ios 17.5.1

### App version

17.5.1

### Screenshots

![IMG_6901](https://github.com/user-attachments/assets/679c3e32-b167-49ab-a6fb-500a74ad092a)

**Comment by jas14** [comment] 2024-09-16 16:38
Duplicate of #2460

**Closed by jas14** 2024-09-16 16:38 UTC
Labels: bug
