### ISSUE TITLE
App enlarged after samsung system update

### ISSUE THREAD

**Issue by Anush-K** [lichess-org/lichobile#2092] opened 2022-04-17 03:21 UTC
**Describe the bug**
The app interface has enlarged after a system update of my Samsung Galaxy F62 mobile. 

**To Reproduce**
1. System Update phone (one UI 4.1 Upgrade 
    (Android 12))
2. App interface enlarges than normal

**Expected behavior**
Expected the app to remain as usual without getting affected by the system update.

**Screenshots**
![Screenshot_20220417-085001_lichess](https://user-images.githubusercontent.com/73292232/163698845-0553b82b-d935-4527-bb6d-4ea49d44416c.jpg)
![Screenshot_20220417-084957_lichess](https://user-images.githubusercontent.com/73292232/163698849-8048fd98-9c5a-4d14-850b-915f9f6fc2ac.jpg)

**Smartphone (please complete the following information):**
 - Samsung Galaxy F62
 - Android version 12 One UI 4.1
 - Chrome 
 - 100.0.4896.127

**Comment by jas14** [comment] 2022-04-17 20:08
Duplicate of #2059 - see the conversation over there, hope this helps!

**Closed by jas14** 2022-04-17 20:08 UTC
Labels: bug
