### ISSUE TITLE
Back button doesn't work on Correspondence games

### ISSUE THREAD

**Issue by discorddioxin** [lichess-org/lichobile#2293] opened 2023-01-27 21:17 UTC
**Describe the bug**
Clicking the back button on my phone does nothing while viewing a correspondence game

**To Reproduce**
1. Create/join a correspondence game
2. Click the back button

**Expected behavior**
Goes to the previous state/activity. If the previous state was the home screen, goes to the home screen.

**Screenshots**
None

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - OS: Android 11
 - Mobile App
 - v8.0.0

**Additional context**
None

**Comment by jas14** [comment] 2023-01-27 23:18
Duplicate of #2272

**Closed by jas14** 2023-01-27 23:18 UTC
Labels: bug
