### ISSUE TITLE
Rating graphs missing

### ISSUE THREAD

**Issue by fyodor1** [lichess-org/lichobile#2267] opened 2022-12-13 12:29 UTC
The rating graphs / charts that showed your rating progress over time in the various categories (bullet, blitz, etc) is no longer showing in the android app (v. 7.16.1). 

To reproduce, simply click menu -> profile -> bullet (or blitz, rapid etc).

There used to be a graph showing the rating progress over time at the top. Now there isn't. The rest of the stats page appears to show correctly.

Android 12 (One UI 4) and 13 (One UI 5), Samsung S20 FE 5G.
Lichess version  7.16.1.

This appears to have been an issue for a while: https://lichess.org/forum/lichess-feedback/progress-graph-disappeared

It may be worth noting that the users who confirmed the problem and reported their phone model both used Samsung phones (as do I).

**Comment by jas14** [comment] 2022-12-14 02:29
Duplicate of #1668.

**Comment by nackerley** [comment] 2022-12-20 14:43
Same issue here, but on a Fairphone 3 running Android 11. The lichess forum thread posted above has multiple reports of the issue on iOS, suggesting it isn't hardware- or OS-specific.

**Comment by meenbeese** [comment] 2022-12-21 14:51
I have the same issue on a Xiaomi (A12) since a few weeks. I can still use the web to see my or others' rating graphs but it's completely broken on mobile. This is very annoying, to say the least.

**Closed** 2022-12-25 13:33 UTC
Labels: bug
