### ISSUE TITLE
Typo in about page

### ISSUE THREAD

**Issue by Matthew-Tyrone-Campbell** [lichess-org/lichobile#2239] opened 2022-11-13 19:07 UTC
On the about page there is a typo reading: lichess would not exist without the thousands of hours of time from volunteers, both from website devs and mobile devs, who create new features and/or bugs.

**Comment by jas14** [comment] 2022-11-13 20:01
@Matthew-Tyrone-Campbell I can't tell at first glance what the issue is here, please highlight the typo and what correction needs to be made

**Comment by Matthew-Tyrone-Campbell** [comment] 2022-11-14 02:22
create new features and/or bugs.

**Comment by jas14** [comment] 2022-11-14 02:28
I think the "and/or bugs" is meant to be funny. 😉

**Comment by Matthew-Tyrone-Campbell** [comment] 2022-11-14 06:06
🤣

**Comment by Matthew-Tyrone-Campbell** [comment] 2022-11-14 06:06
I like it

**Comment by jas14** [comment] 2022-11-15 00:21
Excellent — in that case I'll close the issue

**Closed by jas14** 2022-11-15 00:21 UTC
Labels: bug
