### ISSUE TITLE
Timer does not display on Galaxy Z fold 3 while unfolded

### ISSUE THREAD

**Issue by royce212** [lichess-org/lichobile#2080] opened 2022-04-04 21:39 UTC
When attempting to play on my Galaxy Z Fold 3's main screen using the Lichess android app, the timer cannot be seen anywhere onscreen. This happens consistently in all timed games. Timer displays as intended on the more narrow front display.

**Comment by jas14** [comment] 2022-10-03 14:19
Duplicate of #1635

**Closed by jas14** 2022-10-03 14:19 UTC
