### ISSUE TITLE
Putting lichess in background considered leaving the game

### ISSUE THREAD

**Issue by radres** [lichess-org/lichobile#2174] opened 2022-08-19 19:58 UTC
phone hardware
iphone mini 12

phone operating system version
ios 16 beta

version of lichess mobile beta
V7..15.2

steps to reproduce
Keep lichess in background

description of the observed behavior
Putting lichess in background considered leaving the game

description of the expected behavior
It should be just as in a browser in which if user is not actually closing the tab, browsing other apps in the phone should not be considered as leaving the game

**Comment by jas14** [comment] 2022-08-21 16:44
Duplicate of #1159

**Closed by jas14** 2022-08-21 16:44 UTC
