### ISSUE TITLE
Lichess mobile app bug

### ISSUE THREAD

**Issue by excaliam** [lichess-org/lichobile#2348] opened 2023-04-24 09:57 UTC
![Screenshot_2023-04-24-00-12-17-25_86d667449b00b848f46d695606363a65](https://user-images.githubusercontent.com/131662676/233963609-6b2135b1-2ecf-49bb-9e7f-07f4bae029ab.jpg)
![Screenshot_2023-04-24-00-11-51-95_86d667449b00b848f46d695606363a65](https://user-images.githubusercontent.com/131662676/233963626-49a52ec3-3c28-41fa-bb37-b31cad465a65.jpg)
![Screenshot_2023-04-24-00-09-57-46_86d667449b00b848f46d695606363a65](https://user-images.githubusercontent.com/131662676/233963640-cf069e15-acd6-49ab-bf37-33d8030d0602.jpg)
![Screenshot_2023-04-24-00-09-53-84_86d667449b00b848f46d695606363a65](https://user-images.githubusercontent.com/131662676/233963660-afa29ab3-f963-476c-a98f-60b698a9f6dc.jpg)
as you can see in picture black move but black king underattack and i cant move i lost the game because my time is over

**Comment by Dan5982** [comment] 2023-04-24 20:24
I had the same bug hit me twice today! First to my opponent, and I just kept adding time to him and it eventually showed him my move and let him play. Just now I was the one who couldn't see my opponent's move or make a move, and lost when my time expired. Very frustrating!!!

**Comment by ekoppel** [comment] 2023-05-16 15:26
The bug appears to be that white's 31st move was duplicated as black's move as well

**Comment by snicholsdev** [comment] 2023-06-29 23:05
This happens to me every time an opponent makes a move while I'm looking at the side-scroll list of my ongoing games. If I tap outside of it, then reopen the list, it's back to normal.

**Comment by jas14** [comment] 2024-10-08 05:15
Duplicate of #1012

**Closed by jas14** 2024-10-08 05:15 UTC
Labels: bug
