### ISSUE TITLE
LichessTV responds differently based on how the user navigates to the page.

### ISSUE THREAD

**Issue by rorymulcahey** [lichess-org/lichobile#2078] opened 2022-04-04 07:43 UTC
**Describe the bug**
The time interval (bullet, blitz, etc) on Lichess TV cannot be changed if the screen was opened from the home screen and clicked on the active game to get to lichess TV. However, if "watch games" from the triple line menu (upper left) is clicked instead, then the time interval can be changed and everything works as intended.

**To Reproduce**
1. Go to home screen mobile lichess
2. Scroll down to the active live gameboard currently displaying lichess TV.
3. Click on the active, top game, which will move the user from the home screen displaying the game, to lichess TV.
4. Click the "Lichess TV" text top-center that also displays the time interval (to the right of the triple line menu and left of the friends panel).
5. Try to change the time interval to ultrabullet, bullet, blitz, or anything that is not the current one, and it will not change.

**Expected behavior**
The user should be able to change the time interval. If lichess TV is accessed from the triple line menu (upper left), then "Watch TV", instead of the home screen, then the time interval (bullet, blitz, etc) can be changed.

**Screenshots**
Unavailable.

**Smartphone (please complete the following information):**
 - Device: Samsung 7
 - OS: Andriod 7
 - Browser: N/A (using app)
 - Version: N/A

**Additional context**
Thanks for the awesome development you do mate. Big fan of lichess.

**Comment by jas14** [comment] 2022-04-04 10:50
Duplicate of #1740

**Closed by jas14** 2022-04-04 10:50 UTC
Labels: bug

**Comment by rorymulcahey** [comment] 2022-04-04 20:33
Based on the description of #1740
<https://github.com/lichess-org/lichobile/issues/1740> this issue is
different because the way both issues arrive at the same problem is through
different paths.

This Ticket (#2078) explicity states that using the upper left menu
(hamburger menu) actually works. Whereas in #1740 it does not. Ticket 2078
arrives at this issue through the home menu screen exclusively.

**Comment by jas14** [comment] 2022-04-04 22:39
@rorymulcahey thanks for the report, I believe the root cause for the seemingly different issues is the same: https://github.com/lichess-org/lichobile/issues/1740#issuecomment-874027734

If that issue ends up fixed and this issue somehow is not, do comment here and we'll reopen it
