### ISSUE TITLE
Ratings not visible

### ISSUE THREAD

**Issue by shrey2708** [lichess-org/lichobile#1466] opened 2020-12-25 09:38 UTC
![Screenshot_2020-12-25-15-04-17-532_org lichess mobileapp](https://user-images.githubusercontent.com/76584392/103130394-8aba5880-46c2-11eb-97b9-3dd98377dfd5.jpg)
**Describe the bug**
My puzzle ratings are not visible.

**To Reproduce**
1. Go to 'puzzles'
2. Click on 'rating icon'

**Expected behavior**
A graph of my ratings should be visible.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Redmi k20 pro]
 - OS: [android 10]
 - Browser [app]

**Additional context**

**Comment by ZackaryWelch** [comment] 2020-12-25 20:13
In getting the same thing on a G7 ThinQ, Android 9

**Comment by jas14** [comment] 2020-12-28 15:20
The ratings graph was intentionally removed in https://github.com/veloce/lichobile/commit/1fbd0edb2992d2afee95a482339d5a5b0c6cfa95 . Per that commit message:

> in v2, the rating graph is gone, and recent puzzles are stored locally only. We can do without for now.

**Comment by jensfogh** [comment] 2020-12-31 22:12
I also have this problem. And it is not only the graph not showing - results of solved puzzles does not count to the rating. I think this is a huge problem, since it dramatically reduce the quality of the feature, and make people look for puzzles elsewhere.

**Comment by aleith** [comment] 2021-01-03 06:16
there's more than one issue with the graph mode. i can live without a graph of recent scores, but what was useful was the 20 boxes with scores for last 20 puzzles. I liked returning to failed puzzles to redo them until i recognise the solution immediately.

also the rating math is broken. *failing* a puzzle is adding ~100 points to my puzzle rating.

**Comment by jas14** [comment] 2022-12-08 23:44
Duplicate of #1462

**Closed by jas14** 2022-12-08 23:44 UTC
