### ISSUE TITLE
Screen Shift glitch 

### ISSUE THREAD

**Issue by ncodee** [lichess-org/lichobile#1877] opened 2021-10-07 07:47 UTC
**Describe the bug**
When playing a game the interface shifts below the notch.

**To Reproduce**
1. Random/Unable find root cause

**Expected behavior**
Behave as normal and not shift the app screen down.

**Screenshots**
![2CA9BCD0-3B18-4507-B19A-62B5780A0001](https://user-images.githubusercontent.com/52791179/136341411-69bf0648-1db4-49e7-8064-2c4351b99d60.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: 15.1 Beta 3
 - Version 7.11.3

**Additional context**
-

**Comment by veloce** [comment] 2021-10-18 16:00
Please provide steps to reproduce if you are constantly seeing this issue, as I can't reproduce right now.

**Comment by captnswing** [comment] 2021-11-18 18:30
@veloce steps to reproduce (on my iOS 15 phone): 

- play a 5+0 Bitz game against online opponent
- finish game (resign/abort doesn't seem to trigger the bug)
- start new 5+0 game ("new opponent" or from homepage)

when the new game starts, the screen shifts downwards. after a few games, the hamburger menu in the bottom left becomes impossible to reach

**Comment by bvbeek** [comment] 2021-11-19 23:42
Same issue here on a iPhone 11 iOS 15.1
Every game I start I see the screen moved down. Then I’m almost unable to click on the bottom menu items.

**Comment by veloce** [comment] 2021-11-21 16:42
Still cannot reproduce. Please share as much context as possible:
- game settings (board, piece set, ...)
- using an account, or as anonymous?
- is it a random behaviour or not?
- any other useful info...
-

**Comment by ncodee** [comment] 2021-11-22 01:29
More glitches: 
![C9440A47-1118-4DC4-B4F6-00C4B2106A00](https://user-images.githubusercontent.com/52791179/142788027-8e7433c9-508e-4810-83ee-b5904a5da221.png)

- Game Settings: Quick pairing (any size)
- Both Anonymous/Account
- Random behaviour

I’m not sure what else we can provide that would be helpful. Do you not have an iOS device on hand to test?

**Comment by eshirvana** [comment] 2021-11-22 20:40
I have this issue as well on:

    Device: iPhone 11 Pro
    OS: ios 15.1
    Version 7.13.1

**Comment by jas14** [comment] 2021-11-23 11:58
[The secondscreenshot provided by @ncodee ](https://github.com/veloce/lichobile/issues/1877#issuecomment-974992257) notably is rendering the "Anonymous" name label and the clock in two separate rows. Not so with the first one, but maybe that'll be a clue for us.

**Comment by bvbeek** [comment] 2021-11-26 21:14
Please can someone fix this terrible bug?  It can be easy reproduce by just play a game. When start the second game the glitch is there.

**Comment by tfeldmann** [comment] 2021-12-01 01:27
https://user-images.githubusercontent.com/385566/144155007-8a2e87dc-94a2-4f12-8e4b-50e566ac9e65.MOV


Made a video. Happens 100% reproducible on iPhone 12, iOS 15.1.1 (19B81)

**Comment by Baikalcadillac** [comment] 2021-12-02 10:39
Happens on iPhone X, iOS 15.1. Not sure how to reproduce, but what I've noticed that this shift happens after analyzing games. 
Also side menu can misalign sometimes, possibly for same reason.

**Comment by jerweb63** [comment] 2021-12-04 14:29
I opened a duplicate bug report but closed it because it seemed to have cleared up. Undo, it did not actually 


![88A22531-E0DD-4572-A8CC-8FBB9F308DC2](https://user-images.githubusercontent.com/8494662/144713199-5729d6e7-df8a-4bec-8730-de96d19cfeef.jpeg)

**Comment by jas14** [comment] 2021-12-04 21:43
Just downloaded the XCode beta to get the iOS 15.2 simulator. Still can't reproduce. Also can't reproduce on an iPad with iOS 15.1.

Unfortunately it doesn't appear that Apple has released an iOS 15.1 simulator, so until someone with debugging capability and a physical device running iOS 15.1 comes along, we're out of luck...

**Comment by knutole** [comment] 2021-12-07 00:07
I can reproduce:
1. open app
2. play game until end
3. exit app (soft exit)
4. reenter app. it's now glitched.

![image](https://user-images.githubusercontent.com/2197944/144942280-f788d88d-afca-4632-aba2-0b7c5d9dc9da.png)

I basically get this a lot when exiting, reentering app.

iOS 15.1.1 and iPhone 13 Pro.

**Comment by jerweb63** [comment] 2021-12-14 09:41
This bug is just excruciatingly annoying. It should be relatively easy to reproduce by updating to ios 15.1. Please fix!! 😩

**Comment by bvbeek** [comment] 2021-12-16 16:30
Any news about this issue?

**Comment by eshirvana** [comment] 2021-12-16 18:47
Still have the same issue on ios 15.2

**Comment by amirz-sb** [comment] 2021-12-18 11:19
Have the same issue, happens a lot, extremely annoying to the point of giving up.
Please fix this!!  Happy to help in any way I can!

**Comment by ncodee** [comment] 2021-12-25 18:21
I'm not sure if the latest version fixed the issue, or whether the new iOS beta I am using, but the issue seems to have to fixed for me. I hadn't encountered this issue anymore on iOS 15.3 Beta 1, also it seems to have been working good on iOS 15.2.

Would be great if anyone else can confirm.

**Comment by Baikalcadillac** [comment] 2021-12-27 07:23
After updating to iOS 15.2 screen doesn't shift anymore (on iPhone X).

**Comment by jerweb63** [comment] 2021-12-29 09:42
I must say that I have not encountered this bug anymore since the update to iOS 15.2.

**Comment by alectrocute** [comment] 2022-01-15 15:12
Still a problem on an iPhone 12 Pro Max.

**Comment by jas14** [comment] 2022-01-15 16:59
@alectrocute what is your iOS version?

**Comment by alectrocute** [comment] 2022-01-15 17:01
> @alectrocute what is your iOS version?

iOS 15.2.1, sorry; Should have included that.

 I should use this as an opportunity to note this issue can’t be reproduced inside Lichess TV (don’t know if anybody is using that to test/attempt to reproduce).

**Comment by ary** [comment] 2022-01-18 22:12
I can confirm that upgrading to iOS 15.2.1 on my iPhone 12 mini resolves the issue for me as well.

**Closed** 2022-03-05 09:00 UTC
Labels: can't reproduce
