### ISSUE TITLE
When I reaches to promotion square I can't exchange the pawn into any thing and it's gave me empty line 

### ISSUE THREAD

**Issue by Amr243** [lichess-org/lichobile#2294] opened 2023-01-28 05:08 UTC
Hi lichess support when I play the games and reaches to promotion square I can't exchange the pawn into any thing and it's gave me empty line how can I fix that and thanks for reading 

![IMG_٢٠٢٣٠١٢٤_٠٢١٧١٥](https://user-images.githubusercontent.com/123793787/215243221-e8f9393f-6598-4fc3-8de8-e89ca602be71.jpg)

**Comment by jas14** [comment] 2023-01-28 17:21
Duplicate of #2289

**Closed by jas14** 2023-01-28 17:21 UTC
Labels: bug
