### ISSUE TITLE
Is it possible to add the Puzzle Storm ont the app?

### ISSUE THREAD

**Issue by upavloff** [lichess-org/lichobile#2141] opened 2022-06-29 13:50 UTC
I would like to have the puzzle storm category on my phone.

I would love to be able to play it everywhere.

Thanks for your work!

**Comment by jas14** [comment] 2022-06-29 14:39
Duplicate of #1583. Please give that issue a thumbs-up so we can gauge interest. (It's a very popular feature request, I too would like it eventually 🙂)

**Closed by jas14** 2022-06-29 14:39 UTC
