### ISSUE TITLE
No board bug

### ISSUE THREAD

**Issue by Titomc123** [lichess-org/lichobile#2357] opened 2023-05-18 22:30 UTC
![Screenshot_20230518-192405-587](https://github.com/lichess-org/lichobile/assets/134017170/fd02d772-1f46-4fd2-8b53-05b55b473779)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saint-thomas-more** [comment] 2023-05-23 08:18
Same for me. No changes were done by me beforehand. I managed to make the board appear by switching to another board theme: from Wood 4 to Maple or Blue.

![Screenshot_2023-05-23-11-50-13-489_org lichess mobileapp](https://github.com/lichess-org/lichobile/assets/126619536/60275556-af69-479f-88ce-c545e4cf040a)

**Comment by jas14** [comment] 2023-05-25 10:25
Duplicate of #2354.

**Closed by jas14** 2023-05-25 10:25 UTC
Labels: bug
