### ISSUE TITLE
Analysis works 20% of the time 

### ISSUE THREAD

**Issue by heathcliffsisnotavailable** [lichess-org/lichobile#2035] opened 2022-02-24 01:25 UTC
I promise I’ll donate $100/year if the analysis actually worked on the mobile app. It’s just crushing seeing that hour glass and knowing no matter how long you sit there it doesn’t matter. Nothing is coming. The hour glass haunts my dreams.

**Comment by jas14** [comment] 2022-02-24 01:28
Probable duplicate of #2032

**Comment by veloce** [comment] 2022-02-24 09:34
Please share OS/phone information and anything else useful if you want a fix to happen. This issue is hard to reproduce. Thanks.

**Comment by veloce** [comment] 2022-03-05 07:05
Try to lower number of cpu cores to see if it helps. You can try with the memory too. Thanks.

**Comment by veloce** [comment] 2022-03-05 07:06
Closing as duplicate of #2032

**Closed** 2022-03-05 07:07 UTC
Labels: bug
