### ISSUE TITLE
Said opponent was in check when I was actually in check, wouldn’t let me move

### ISSUE THREAD

**Issue by Johnnymaaaac** [lichess-org/lichobile#2306] opened 2023-02-09 23:13 UTC
I was in check but the opponent king was lit red. Furthermore, I couldn’t move, I could only pre-move, as if the opponent hadn’t moved yet, even though their piece had just moved and was green. The clock ran out and I was warned for letting the clock run out. What just happened?

**Comment by Deleplace** [comment] 2023-02-10 09:40
Screenshot?

**Comment by jas14** [comment] 2023-02-11 18:34
Duplicate of #1012 .

Thanks for the report. This appears to belong to an class of errors that seems to stem from an odd number of more moves in the current tree being missing. The app consequently does not permit moves by the appropriate user, highlights the wrong king, etcetera. It's been unfortunately extremely difficult to reproduce and debug.

**Closed by jas14** 2023-02-11 18:34 UTC
Labels: bug
