### ISSUE TITLE
Unable to promote pawns

### ISSUE THREAD

**Issue by plaf-git** [lichess-org/lichobile#2414] opened 2023-11-15 20:00 UTC
### What happened?

When my pawn arrives on the promotion line, the white panel opens for choosing the promotion but it is empty, I cannot choose any piece so I cannot promote.

### How can we reproduce the bug?

1. Start an Offline-Computer game
2. Move a pawn to promotion line => a white panel opens in the middle of the screen, but it is empty. Any click inside or outside the white panel have no effect. I can only choose the Back button to go back to the game, and choose another move.

### Expected behavior

I suppose the white panel should display the pieces I can choose to promote a pawn

### Device

LG G2 mini (LG-D620R)

### Operating system

Android 5.0.2

### App version

v7.16.1

### Screenshots

![Screenshot_2023-11-15-20-28-01](https://github.com/lichess-org/lichobile/assets/145739838/5e2de8c3-71c3-4b7c-baea-4dcd52f1a90b)

### Additional context

My phone is stuck on Android 5.0.2, I cannot install Lichess v8.0.0 as it requires at least 5.1. So close and yet so far :-)
Thanks in advance if you can do something !

**Comment by jas14** [comment] 2023-11-19 23:08
Duplicate of #1793.

**Closed by jas14** 2023-11-19 23:08 UTC
Labels: bug
