### ISSUE TITLE
Promotion to Queen bug on Lichess 8.0.0.

### ISSUE THREAD

**Issue by endriu11111111** [lichess-org/lichobile#2382] opened 2023-07-26 13:07 UTC
I also have a problem with promoting to queen in the Lichess game in the Android app. The application version is 8.0.0, Android version 10, phone model: Motorola One (XT-1941-4).

Please help me kindly.
![Screenshot_20230726-150857.png](https://github.com/lichess-org/lichobile/assets/140278579/5cfa9b88-ce40-4b1b-9726-45f6c2627a29)

**Comment by jas14** [comment] 2023-11-19 23:08
Duplicate of #1793.

**Closed by jas14** 2023-11-19 23:08 UTC
