### ISSUE TITLE
Lichess TV doesn't change game type

### ISSUE THREAD

**Issue by shah-xad** [lichess-org/lichobile#2031] opened 2022-02-15 17:56 UTC
**Describe the bug**
Whenever I open Lichess TV from the main screen, it doesn't change the game type from the top dropdown. It always keeps the same game. However, if I open Lichess TV from the side menu then it works.

**To Reproduce**
1. Go to Lichess TV from the main screen
2. Click on the top
3. Choose any version
4. It'll remain the same

**Expected behavior**
It should change the game as per selection from the main screen Lichess TV.

**Screenshots*
![WhatsApp Image 2022-02-15 at 10 51 27 PM](https://user-images.githubusercontent.com/32363363/154120698-1376da37-1cac-4c4f-a028-23be904ee50d.jpeg)
*

**Smartphone (please complete the following information):**
 - Device: Huawei
 - OS: Android
 - Version 10

**Comment by jas14** [comment] 2022-02-16 23:15
Duplicate of #1740

**Closed by jas14** 2022-02-16 23:15 UTC
Labels: bug
