### ISSUE TITLE
Android create Study ... isn't working

### ISSUE THREAD

**Issue by Galactus30000** [lichess-org/lichobile#2445] opened 2024-03-09 21:50 UTC
### What happened?

my Chess Gym colleagues keep telling me to create a Study for my past games and yet when I go to do this on my Android Lichess app, it is not working. Generating new study not appearing 

### How can we reproduce the bug?

Try to generate a new Study from the Android app

### Expected behavior

expected to able to generate a new study

### Device

Galaxy S8

### Operating system

Android

### App version

v8.0.0

**Comment by jas14** [comment] 2024-10-08 05:10
Duplicate of #1240

**Closed by jas14** 2024-10-08 05:10 UTC
Labels: bug
