### ISSUE TITLE
Game zoomed out

### ISSUE THREAD

**Issue by Eirikalv1** [lichess-org/lichobile#2155] opened 2022-07-29 12:41 UTC
**Describe the bug**
Game is zoomed out.

**To Reproduce**
Open the app on Galaxy A52.

**Expected behavior**
UI to be formatted correctly.

**Screenshots**
![Screenshot_20220729-141849_lichess](https://user-images.githubusercontent.com/83610862/181760774-29a7a110-6519-4379-9196-4e89cebb124a.jpg)

**Smartphone**
 - Device: Samsung Galaxy A52.
 - OS: Android 12.

**Additional context**
I have seen similar bug reports on Samsung, but I have not found a working fix. Changing the system font size, temporarily fixes the UI until opening the app next time.

**Comment by jas14** [comment] 2022-07-29 13:10
Duplicate of #2059.

@Eirikalv1 thanks for the report — I'm going to close this as a duplicate as noted above, seems to be the same issue. Give that one a thumbs-up so we can continue to gauge impact.

**Closed by jas14** 2022-07-29 13:10 UTC
Labels: bug
