### ISSUE TITLE
Create New study

### ISSUE THREAD

**Issue by ejad9** [lichess-org/lichobile#2508] opened 2024-09-24 21:23 UTC
### What happened?

Impossible to create a study on my mobile 

### How can we reproduce the bug?

1. Go to navigation bar
2. Clic on "study"
3. Then i cant see any "+" or "New study" button. I can only see the list of the more popular studies

### Expected behavior

See a "+" button above the liste of popular studies to create my own study

### Device

Redmi Note 11

### Operating system

Android 13 TKQ1.221114.001

### App version

v8.0.0

### Screenshots

![Screenshot_2024-09-24-23-24-42-095_org lichess mobileapp](https://github.com/user-attachments/assets/d40b7216-40c5-4697-b1b4-e9d1196186f7)

**Comment by jas14** [comment] 2024-10-08 05:10
Duplicate of #1240

**Closed by jas14** 2024-10-08 05:10 UTC
Labels: bug
