### ISSUE TITLE
Study issue 

### ISSUE THREAD

**Issue by Ankanahadoww** [lichess-org/lichobile#2512] opened 2024-09-30 02:39 UTC
### What happened?

When selecting any study, it just opens up an empty board and a loading animation, but the loading never resolves.

### How can we reproduce the bug?

1. Go to study section 
2. Open any study 
3. You will find the bug

### Expected behavior

Study section is opening as soon as possible 

### Device

Iqooz7

### Operating system

Android 14

### App version

V8.0.0

**Comment by jas14** [comment] 2024-10-08 05:08
Duplicate of #2509

**Closed by jas14** 2024-10-08 05:08 UTC
Labels: bug
