### ISSUE TITLE
Study interactive lessons shows the solution in the APP

### ISSUE THREAD

**Issue by drdoom** [lichess-org/lichobile#2169] opened 2022-08-17 15:09 UTC
When I open a Study that has chapters set as  Interactive lessons it shows me all the lines and solutions instead of hidding them as the lichess.org web does.
This is a huge bug because students can see the interactive lesson solutions.

First demostration:
Create a new study, new chapter set it to interactive lesson, make a few moves, open the study in the web browser and it works ok, but open the study with the APP (lichess for android 7.16.0) and you could see all the moves.

Second demostration:
Try this study in the web browser
https://lichess.org/study/77p9MZr4/UNUcui6E
It works as usual (interactive lesson)
Open it again in the lichess APP, see attached screenshot.

![WhatsApp Image 2022-08-17 at 4 41 38 PM](https://user-images.githubusercontent.com/3505828/185174533-2b69f9c7-7f74-4488-8efc-f28bf78b1cca.jpeg)

**Comment by jas14** [comment] 2022-08-17 15:15
@drdoom seems like this is a duplicate of #1505 , if that's the case you can close this issue and give that one a thumbs-up to indicate you're interested in a fix

**Closed** 2022-08-17 15:21 UTC
Labels: bug
