### ISSUE TITLE
There is no lobby in mobile app

### ISSUE THREAD

**Issue by chr-bakk** [lichess-org/lichobile#2172] opened 2022-08-19 05:03 UTC
Only quick pairing and correspondence.
I expect it to be like the web page.
I have a galaxy S10 and Android 10.
![Screenshot_20220819-064147_lichess](https://user-images.githubusercontent.com/9739167/185546407-70838220-6e7e-420b-bf7b-de9fa1b2cc68.jpg)

**Comment by jas14** [comment] 2022-08-19 09:43
Duplicate of #1149

**Closed by jas14** 2022-08-19 09:43 UTC
