### ISSUE TITLE
Wrong king highlights for checking

### ISSUE THREAD

**Issue by arunahk** [lichess-org/lichobile#2082] opened 2022-04-07 10:48 UTC
**Describe the bug**
White king highlights when black king checked mate

**To Reproduce**
https://lichess.org/sfrpbxGT/white#29

**Expected behavior**
Black king should be highlighted

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Huawei P30 Pro
 - OS: Android 10
 - Version 
 - 
![Screenshot_20220407_224157_org lichess mobileapp](https://user-images.githubusercontent.com/1442701/162181861-cdb84582-6cd5-4b64-a533-2fb1f5344989.jpg)

**Comment by jas14** [comment] 2022-04-07 11:07
Duplicate of #1012.

**Closed by jas14** 2022-04-07 11:07 UTC
Labels: bug
