### ISSUE TITLE
I cant get promotion

### ISSUE THREAD

**Issue by jasio186** [lichess-org/lichobile#2214] opened 2022-10-12 20:01 UTC
When I played as an Anonymous I couldnt got promotion. I have a photo taken in that moment as screenshot. I can send it. If you want give me info to janusz.sroda@poczta.fm.
Greetings You and thanks for amazing project.

**Comment by jas14** [comment] 2022-10-12 21:02
Probable duplicate of #1793

**Closed by jas14** 2022-10-12 21:02 UTC
