### ISSUE TITLE
Disable swiping action during a match

### ISSUE THREAD

**Issue by biergit** [lichess-org/lichobile#2114] opened 2022-05-23 10:27 UTC
**Is your feature request related to a problem? Please describe.**
On a Pixel phone playing blitz games is hardly possible because of the annoying swipe action that triggers whenever you move a piece from the a or h lines unless you are veeeery precise.

**Describe the solution you'd like**
Best option: Remove the swipe action.
Second best: Provide a setting to allow to disable it.

**Comment by jas14** [comment] 2022-05-23 10:58
Duplicate of #1027

**Closed** 2022-05-23 10:58 UTC
