### ISSUE TITLE
Broadcast in mobile app

### ISSUE THREAD

**Issue by smalints** [lichess-org/lichobile#2175] opened 2022-08-23 18:12 UTC
Please add a tournament broadcast feature for mobile too. As Implemented in the web version.

![image](https://user-images.githubusercontent.com/19852104/186233119-175938bc-e3ce-4a78-bf9b-494c4475dbcf.png)

Thank you.

**Comment by jas14** [comment] 2022-08-23 23:36
Duplicate of #1284

**Closed by jas14** 2022-08-23 23:36 UTC
