### ISSUE TITLE
Rating graph is not displayed on the iOS app

### ISSUE THREAD

**Issue by broslavski** [lichess-org/lichobile#1476] opened 2021-01-02 15:14 UTC
**Describe the bug**
Rating graph is not displayed on the iOS app.

**To Reproduce**
1. Open Liches iOS App.
2. Tap sandwich icon to open side menu.
3. Tap **Learn / Puzzles** menu item to open Puzzles chess board.
4. Tap Graph icon (1-st left on the bottom bar) to open **Your puzzle rating** window.
5. There is no graph of progress in puzzles.

**Expected behavior**

**Screenshots**
<img src="https://user-images.githubusercontent.com/39467594/103460189-f9c82a80-4d1c-11eb-851c-8970b08ab922.jpg" width="200">

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 14.3
 - App version: 7.6.0

**Additional context**
Previous versions of the program had no such problems.

**Comment by fynsta** [comment] 2021-01-02 16:39
Please google your problem before opening tickets.

Duplicate of #1463 #1466 and others...

**Comment by broslavski** [comment] 2021-01-02 17:15
> Please google your problem before opening tickets.
> 
> Duplicate of #1462, #1466 and others...

Is there a solution to this problem?

**Comment by jas14** [comment] 2022-12-08 23:44
Duplicate of #1462

**Closed by jas14** 2022-12-08 23:44 UTC
