### ISSUE TITLE
Tactical puzzles not awarding rating points

### ISSUE THREAD

**Issue by tomt28** [lichess-org/lichobile#1310] opened 2020-07-15 05:08 UTC
**Describe the bug**
Tactical puzzles not awarding rating points for correct answers out removing rating points for incorrect answers. It was working for a long time then just stopped completely. Hasn't worked for weeks.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device:  Sony  Xa1
 - OS: Android

**Additional context**

**Comment by MglMX** [comment] 2020-07-15 06:50
There is a ªsync and refresh saved puzzles" button in the puzzles section. If you click it, the puzzle will be synced again and the ratings should work.

**Comment by jas14** [comment] 2022-12-31 21:31
Duplicate of #1363

**Closed by jas14** 2022-12-31 21:31 UTC
