### ISSUE TITLE
Update timestamp in the main preview when iterating through moves after game ends.

### ISSUE THREAD

**Issue by vishalsatam** [lichess-org/lichobile#2202] opened 2022-09-28 02:14 UTC
**Is your feature request related to a problem? Please describe.**

When I'm replaying my game after it has ended, I find myself wanting to know what is the time remaining for each players per move cycled using the navigation bar below. This would help in showcasing the full context of the decisions made for every move.
This feature request is for the Android version of the app.

**Describe the solution you'd like**
While replaying a game in mobile app after it has ended, please update the time remaining while iterating through moves.

**Describe alternatives you've considered**
The timestamp is available when using the Analyzer tool, but it would be nice in the main view while replaying a finished game.

**Additional context**
![Untitled](https://user-images.githubusercontent.com/30029252/192671570-34afed3d-a02d-461f-a2af-ba231984faec.png)

**Comment by jas14** [comment] 2022-10-03 14:17
Duplicate of #1406

**Closed by jas14** 2022-10-03 14:17 UTC
