### ISSUE TITLE
Box that comes after game stays for minutes

### ISSUE THREAD

**Issue by hobbitcoder** [lichess-org/lichobile#2163] opened 2022-08-08 19:44 UTC
The black box that has game results (black resigned, for example) stays for minutes
**To Reproduce**
Right after game is played

Smartphone: samsung galaxy A01 core

**Comment by jas14** [comment] 2022-08-08 21:55
Thanks for the report, @hobbitcoder — this issue is a duplicate of #1481  , but please give that issue a thumbs up so we can continue to gauge impact.

**Closed by jas14** 2022-08-08 21:55 UTC
Labels: bug

**Comment by hobbitcoder** [comment] 2022-08-09 03:40
What do you mean by a thums up?

**Comment by jas14** [comment] 2022-08-09 11:27
<img width="926" alt="Screen Shot 2022-08-09 at 7 26 40 AM" src="https://user-images.githubusercontent.com/569991/183636358-4b06b789-b199-4071-abfe-ceae76360912.png">
