### ISSUE TITLE
Empty promoting dialogue no pieces are available

### ISSUE THREAD

**Issue by imla** [lichess-org/lichobile#2170] opened 2022-08-17 16:01 UTC
**Describe the bug**
After promoting a pawn an empty dialogue pop up, so there is no way to choose a piece !

**To Reproduce**
1. Promote a pawn

**Expected behavior**
The dialogue should give a list of pieces to choose from.

**Screenshots**
![Screenshot_20220817-165452](https://user-images.githubusercontent.com/5209311/185186522-9b0170e6-e832-4a00-a692-2701f82ed06a.png)

**Smartphone (please complete the following information):**
 - Device: nexus 7 2013
 - OS: android 7.1.2

**Additional context**

**Comment by matejplank** [comment] 2022-09-02 21:10
Same problem,help me @jas14

**Comment by jas14** [comment] 2022-09-05 00:35
Duplicate of #1793

**Closed by jas14** 2022-09-05 00:35 UTC
Labels: bug
