### ISSUE TITLE
Cannot promote pawns

### ISSUE THREAD

**Issue by OsheterT** [lichess-org/lichobile#2290] opened 2023-01-24 13:46 UTC
**Describe the bug**
One my pawn reaches the last line, a screen appears to choose what I'd like to promote my pawn to, but there are no pieces on this screen and pressing on it does nothing.

**To Reproduce**
1. Board editor
2. Create a situation where your pawn is before promotion (say a7 for white)
3. Play this board against computer and move pawn to a8
(This also happens in games online, unfortunately. Lost a couple times because of this haha)

**Expected behavior**
The white screen should show the possible pieces

**Screenshots**
![chess](https://user-images.githubusercontent.com/80784147/214312227-40036d75-d2ae-48e4-8994-44fdf49c0b07.jpeg)

**Smartphone (please complete the following information):**
 - Device: huawei p30
 - OS: Android 10
 - Browser: lichess app
 - Version: 8.0.0

**Additional context**
This issue started after I changed the board theme and piece set. I've since changed it back but the issue remains. For now I changed my settings to promote automatically to queen and it works fine, but I cannot promote pawns by myself

**Comment by jas14** [comment] 2023-01-26 02:19
Duplicate of #2289.

**Closed by jas14** 2023-01-26 02:19 UTC
Labels: bug
