### ISSUE TITLE
iOS app Issue - Usernames don’t follow sides when using Flip Board feature

### ISSUE THREAD

**Issue by SILVERCLOUD-ALPHA** [lichess-org/lichobile#2054] opened 2022-03-08 05:56 UTC
I was having issues with the board flipping properly. I noticed that while the board rotated, the usernames associated with each side did not follow the flip board. (Basically only the pieces flipped, but the usernames didn’t follow) Can anyone explain why I’m having this issue? Is anyone else having this issue on their iOS app?

Resolution attempts: 
I have tried doing the flip board function when I’m watching games via lichess TV on the iOS app, and it works there without issue. The issue is only occurring on my games, both daily and live. 

I have tried to uninstall and reinstall the app, but the flip board function does not work properly.

**Expected behavior**
When I use the flip board function, the usernames associated with each side are supposed to follow. Instead, only the pieces flipped, but not the usernames

**Screenshots**
The issue happens on all games I’m playing on, whether it’s with computer, daily, or live.

1 Here is game with computer. Notice how white is on the bottom, black is on the top:

![EE2B7107-F39A-4178-8FE4-A972B8994C4A](https://user-images.githubusercontent.com/101165301/157174913-9cc28a94-75c5-4c17-8850-be358818f624.png)

2 I use the flip board function (the cycling arrows button). Notice that the pieces switched sides, but the usernames and timers did not:

![D9B3BF6F-5504-4D6F-81BD-563D7099E38B](https://user-images.githubusercontent.com/101165301/157175066-7c467c36-ddc4-4b42-a240-264aef6617cc.png)

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: 14.7
 - Browser - N/A
 - Version 7.15.0

**Additional context**
Can anyone explain why this issue is occurring? I have had this issue for a week now. The SLIVERCLOUD-ALPHA Lichess account was just a test account I created today to see if the issue lies in my main account, but it turns out this glitch still exists regardless if you completely make a new account or use your main account you had for years. 

Also, this flip board glitch started ever since I updated the Lichess iOS app a week ago.

In lieu of following the rules regarding multi accounting, I closed the account SILVERCLOUD-ALPHA on Lichess because it was just solely created to test if the bug had to do with my main Lichess account.

**Comment by jas14** [comment] 2022-03-08 11:48
Thanks for the detailed report. This is a duplicate of #1996 and the fix will be released in the next version of the app

**Closed by jas14** 2022-03-08 11:48 UTC
Labels: bug
