### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by mrinal7** [lichess-org/lichobile#2075] opened 2022-04-01 16:48 UTC
![lichess_2022-04-01-22-12-27](https://user-images.githubusercontent.com/18095475/161307184-793b2088-5d64-46f2-a4c1-f3e8a680d580.jpg)

Wrong moves happen due to alignment issue.
Device S20 Fe

**Comment by jas14** [comment] 2022-04-17 20:11
Looks like a duplicate of #2059

**Closed by jas14** 2022-04-17 20:11 UTC
