### ISSUE TITLE
join option issue 

### ISSUE THREAD

**Issue by sambitmaharana9** [lichess-org/lichobile#2281] opened 2023-01-08 15:48 UTC
[**Describe](url) the bug**
the tournament link is created by desktop but not able to join in mobile app. there is no join option available 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jas14** [comment] 2023-01-09 23:31
Duplicate of #1165

**Closed by jas14** 2023-01-09 23:31 UTC
Labels: bug
