### ISSUE TITLE
Viewing moves after match: display clock values from then

### ISSUE THREAD

**Issue by Deleplace** [lichess-org/lichobile#2245] opened 2022-11-21 10:39 UTC
**Is your feature request related to a problem? Please describe.**

After a game, I can click ⏪ ⏩ to navigate through all the moves of the game, which is great. However, the 2 clocks' values are fixed at their end-of-game value, which is not the most helpful in this context.

**Describe the solution you'd like**

It would be more informative to display the exacts values that the 2 clocks displayed when the board reached this state. To understand (or remember) why the player made a specific move, it is useful to take into account whether they were very short on time.

**Additional context**

This feature request applies both when viewing my moves juste after playing, or when viewing a past game from my history.

![image](https://user-images.githubusercontent.com/13508141/203028672-1ba065a7-c036-48c5-9bc5-ae0d7d0aa17c.png)

**Comment by jas14** [comment] 2022-11-23 21:47
@Deleplace , thanks for the detailed note. This is a duplicate of #1406 , so I'm going to close it — please upvote and watch that issue for any development.

**Closed by jas14** 2022-11-23 21:47 UTC

**Comment by Deleplace** [comment] 2022-11-23 23:00
Thank you @jas14 , indeed I had missed #1406 somehow
