### ISSUE TITLE
Blank white bar when promoting pawns

### ISSUE THREAD

**Issue by iSimorgh** [lichess-org/lichobile#2222] opened 2022-10-21 16:40 UTC
**Bug**
When moving a pawn to be promoted, the pop-up bar is blank and there is no way to choose a piece to promote the pawn.

**To Reproduce**
1. Promoting a pawn
2. The pop-up bar is blank
3. No choices available to promote the pawn

**Expected behavior**
To be able to choose a piece to promote the pawn.

**Screenshot**
![IMG_20221021_123412](https://user-images.githubusercontent.com/24422928/197245318-a93ddb7e-0893-483b-97a4-c518ba58c7a6.jpg)

**Device:**
 - Device: Fire Tablet HD 10 (9th generation)
 - OS: Fire OS 7.3.1.6
 - Lichess app Version: 7.16.0

**Comment by jas14** [comment] 2022-10-23 01:59
Duplicate of #1793

**Closed by jas14** 2022-10-23 01:59 UTC
Labels: bug
