### ISSUE TITLE
My pieces get moved by the bot

### ISSUE THREAD

**Issue by Hobbiestoomany** [lichess-org/lichobile#1909] opened 2021-11-10 07:00 UTC
**Describe the bug**
When I play stock fish on the app

https://user-images.githubusercontent.com/94031383/141064640-13a19cfa-aa54-4f6a-8cbf-4d9b1ced1eac.mp4

![Screenshot_20211104-142430_lichess](https://user-images.githubusercontent.com/94031383/141064684-9ad07272-a2e1-4679-8062-d986d01720e8.jpg)
![Screenshot_20211104-142414_lichess](https://user-images.githubusercontent.com/94031383/141064759-26a3a2c1-6ba1-4579-9fbf-434b8b5f8f3c.jpg)
 locally on my Samsung s10 running Android 11, recently it started bugging out by moving MY piece after I move.   In one example, I took the queen with my pawn and then it moved my pawn two squares left as if it was its queen.  (Picture)  In another case , I took a knight.  When I highlight my bishop it shows me knight moves (picture).  In another case,  after I castled it moved my pawn (video)

This seems to happen often.  Maybe every time I play.

**Comment by jas14** [comment] 2021-11-10 12:02
Thanks for the detailed report. Marking as duplicate of #1637 and #1684

**Comment by Hobbiestoomany** [comment] 2021-11-10 19:54
It doesn't require castling.  You can see I didn't castle in two of my examples.  I had a case just now where it froze as soon as I moved my king (no picture), but I'll attach a game where I moved my king and nothing went wrong for awhile,  but then it moved a piece without moving out of check.  Then froze.
![Screenshot_20211110-114750_lichess](https://user-images.githubusercontent.com/94031383/141183732-95234e89-a9f9-4e00-8bb6-78cafa277f69.jpg)

**Comment by Chryslr** [comment] 2021-11-14 09:31
Stockfish vs stockfish bug lol

**Comment by Hobbiestoomany** [comment] 2021-12-30 04:15
This is still happening.   Anything I can do to help debug?

**Comment by Xample** [comment] 2022-01-06 20:50
I’ve the same issue which happened after castling.
iOS lichess v7.13.1

**Comment by jas14** [comment] 2022-09-18 21:08
As noted, duplicate of #1637

**Closed by jas14** 2022-09-18 21:08 UTC
