### ISSUE TITLE
Opponent king gets checked instead of mine, so coudn't play on my turn to move

### ISSUE THREAD

**Issue by chinu27** [lichess-org/lichobile#2404] opened 2023-10-19 18:26 UTC
### What happened?

while playing a rated game on lichess app(android), oppenent put my king under chess but game put his king under chess and i couldn't move the rest of the game thereby resulting in my loss by timeout. Even though i was my turn to move i couldn't

### How can we reproduce the bug?

I tried but could't reporduce it.

### Expected behavior

My king had to be under check insted of opponent so i coulf move my pieces and continue the game

### Device

Samsung Galaxy S20 FE

### Operating system

Android 13

### App version

.7.5.6

### Screenshots

![photo_6165427971930830285_y](https://github.com/lichess-org/lichobile/assets/36701592/8d66434c-ef44-4bcc-8d79-b0cb415bfe14)

### Additional context

please revert the rating that i lost from this match as it happend during a rated game.

**Comment by surfstian** [comment] 2023-12-26 21:15
This bug usually doesn't lock up the board, just marks the wrong king.

You were in check by the knight, did you try to move the king or take the knight?

**Comment by jas14** [comment] 2024-10-08 05:22
Duplicate of #1012, noting PGN is also off: 15. Nf2+ instead of 15... Nf2+ for Black's move.

**Closed by jas14** 2024-10-08 05:22 UTC
Labels: bug
