### ISSUE TITLE
Promoting doesnt work anymore on Android App 

### ISSUE THREAD

**Issue by hackerONrails** [lichess-org/lichobile#2188] opened 2022-09-10 16:52 UTC
Today I updated my android app to the newest version available in Play Store (v7.16.0)

I played in an Crazyhouse tournament, and was in a position where I wanted to promote my pawn. But the promotion selection was just empty! Also clicking where the Queen normally is did not help. I had to start my laptop, and do the promotion there.

And this was already the second time it happened today (one app restart in-between).
![grafik](https://user-images.githubusercontent.com/94439393/189493445-17adf22f-81b6-4c05-9172-8ff1d045bbfe.png)

And just now I also tried deleting all the data from the app, logging in again freshly, but the problem persists.

Can't tell you which version I had before, since I dont update too often.

**Comment by jas14** [comment] 2022-09-10 17:28
Duplicate of #1793.

@hackerONrails, sorry for the trouble. Many people have been reporting this, but we still can't reproduce the issue. It would be helpful if you posted your phone details (OS, device make & model) on #1793 . Thanks in advance

**Closed by jas14** 2022-09-10 17:28 UTC
Labels: bug
