### ISSUE TITLE
Promoting pawn

### ISSUE THREAD

**Issue by matejplank** [lichess-org/lichobile#2179] opened 2022-09-02 21:12 UTC
**Describe the bug**
I camt promote pawn

**Expected behavior**
To promote my pawn but i see empty dialogue

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jas14** [comment] 2022-09-05 00:32
Duplicate of #2170

**Closed by jas14** 2022-09-05 00:32 UTC
Labels: bug
