### ISSUE TITLE
Feature Request: iOS Support for "Magic" Keyboard

### ISSUE THREAD

**Issue by CMDRExorcist** [lichess-org/lichobile#2102] opened 2022-04-28 16:59 UTC
Currently, the iOS app is unusable with the trackpad for the Apple Magic Keyboard on iPad Pro. Whenever the pointer hovers over an element in the app, it turns to a cursor line and will not select any of the app elements. Can we please get support to be able to point and click in the app using the keyboard trackpad?

Thanks,
lichess.org user CMDRExorcist

**Comment by jas14** [comment] 2022-04-30 22:06
Duplicate of #1517

**Closed by jas14** 2022-04-30 22:06 UTC
