### ISSUE TITLE
Time runs out for opponent but I lost

### ISSUE THREAD

**Issue by ND1979** [lichess-org/lichobile#1929] opened 2021-11-28 05:39 UTC
Time for the opponent went to zero and nothing happened. It took for 5 minutes and inspite of the time went off long time ago, screen left as-is... seeing that nothing happens I went to the main menu and when checked in the games archives, seen the message how "I left the game and lost". By tapping on question mark in the top left seen message which reads that there is "PING: a lag between me and the server, SERVER: time to process move on the server".

 My nick is "Donnik" and opponent is "Meda78".

Android, Redmi 6, "Lichess" the last update...

**Comment by harabrat** [comment] 2022-01-15 21:47
Got the same issue, what to do?

**Comment by bonstio** [comment] 2023-04-24 22:32
Still happening. Happens frequently. Makes me want to ditch the app.

https://photos.app.goo.gl/TCDtYqHsu2nwRR8y7

I have a bug report to share.

**Comment by jas14** [comment] 2024-10-08 05:13
Duplicate of #1344.

**Closed by jas14** 2024-10-08 05:13 UTC
