### ISSUE TITLE
Add Swiss tournaments on the app

### ISSUE THREAD

**Issue by ayush191005** [lichess-org/lichobile#2168] opened 2022-08-17 14:19 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ayush191005** [comment] 2022-08-17 14:22
No it is not a problem ...it would just be nice to have Swiss tournaments included in the app.

**Comment by jas14** [comment] 2022-08-17 15:14
Duplicate of #1348

**Closed by jas14** 2022-08-17 15:14 UTC
