### ISSUE TITLE
Game outcome message is stying permanently

### ISSUE THREAD

**Issue by tokarskyi** [lichess-org/lichobile#1272] opened 2020-06-02 22:45 UTC
Hi,

I have iPhone XS, with 13.5 software version. From time to time I have the following issue:
1. End the game
2. Outcome is showing on a transparent message in the middle of the screen. Usually it disappears within second or two.
3. I request a new game, new board opens up, but message with outcome of last game is staying.
4. I only can get rid of it if I restart the app.

I also think it might something to do with opponent offering rematch, but I’m not sure it’s related.

Thanks

**Comment by jas14** [comment] 2022-12-31 21:36
Duplicate of #1481

**Closed by jas14** 2022-12-31 21:36 UTC
