### ISSUE TITLE
Dear Lichess! I can't rotate my phone while I'm playing, so a I can't see my partner, his rate, neither the time. I've got a Samsung Galaxy Fold 2. Would you help me? Thank you, your sincerely

### ISSUE THREAD

**Issue by Optimum1947** [lichess-org/lichobile#1872] opened 2021-10-03 06:25 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**
Dear Lichess! I can't rotate my phone while I'm playing, so a I can't see my partner, his rate, neither the time. I've got a Samsung Galaxy Fold 2. Would you help me? Thank you, your sincerely

**Comment by jas14** [comment] 2022-10-03 14:18
Duplicate of #1635

**Closed by jas14** 2022-10-03 14:18 UTC
