### ISSUE TITLE
Application not working properly  and the screen is black 

### ISSUE THREAD

**Issue by Wizsilk** [lichess-org/lichobile#2358] opened 2023-05-19 09:43 UTC
![Screenshot_20230519-122648_lichess](https://github.com/lichess-org/lichobile/assets/134054011/2b86983e-1b11-4926-91da-4fab278ea61b)
![Screenshot_20230519-122624_lichess](https://github.com/lichess-org/lichobile/assets/134054011/6593fc20-3d75-4087-a497-59d232150ab7)
![Screenshot_20230519-122610_lichess](https://github.com/lichess-org/lichobile/assets/134054011/86f909c1-c1e7-44e3-97b4-17982d4555af)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chesslover2016** [comment] 2023-05-23 02:42
I m with the sabe bug

**Comment by jas14** [comment] 2023-05-25 10:26
Duplicate of #2354.

**Closed by jas14** 2023-05-25 10:26 UTC
Labels: bug
