### ISSUE TITLE
Problem with scrolling

### ISSUE THREAD

**Issue by sysrek** [lichess-org/lichobile#1302] opened 2020-07-06 06:45 UTC
Hi,
It is not possible to scroll down the screens in the Lichess mobile application (version 7.2.0).
Android version 5.1.1.
The application is useless without scrolling.
Scrolling in the main menu works, but
- home
- played games
- languages
or the others no.

**Comment by metinevren** [comment] 2020-07-06 09:31
Seconded! Also cannot view analysis board after a game too. It requires scrolling to view the next/previous move buttons which should already be inside the view without scrolling.

**Comment by ohnekopf** [comment] 2020-08-14 03:35
same problem here. I'm on a Samsung J2 Prime, android version 6.0.1 with lichess app version 7.3.0. can't scroll on the home tab nor anywhere else

**Comment by jas14** [comment] 2022-12-31 21:32
Duplicate of #1281

**Closed by jas14** 2022-12-31 21:33 UTC
