### ISSUE TITLE
Scaling and shape errors

### ISSUE THREAD

**Issue by Budfy5** [lichess-org/lichobile#2110] opened 2022-05-11 08:44 UTC
Hello, Lichess mob app looks bad on the main page (first ans second screenshot).
![Screenshot_20220511-093708_lichess](https://user-images.githubusercontent.com/105343810/167808317-46d218e3-5a79-4281-a871-d2e2da91aca7.jpg)
![Screenshot_20220511-085732_lichess](https://user-images.githubusercontent.com/105343810/167808326-5aba49da-92cd-4a42-8f66-8a0b50cb9624.jpg)

It is newest app vetsion.
Phone is Samsung S20 FE.
Software version in following screenshot.
![Screenshot_20220511-094204_Settings](https://user-images.githubusercontent.com/105343810/167808472-f9eaf6e5-5b8b-4bbf-94f3-847b838afe72.jpg)

![Screenshot_20220511-094210_Settings](https://user-images.githubusercontent.com/105343810/167808399-68f43a0b-8f9c-4238-b8a6-02c9c543260c.jpg)

Thanks in advance for help!

**Comment by jas14** [comment] 2022-05-11 11:41
Duplicate of #2059

**Closed by jas14** 2022-05-11 11:41 UTC
Labels: bug
