### ISSUE TITLE
Can't convert pawn

### ISSUE THREAD

**Issue by Matzthias** [lichess-org/lichobile#2190] opened 2022-09-11 20:08 UTC
Hello guys I have this problem from time to time that I can't convert my pawns. I had this like 5 times now I'm very confused.
Playing on Android
I lost the game because of that... 
![Screenshot_20220911-215603](https://user-images.githubusercontent.com/113310960/189546919-0c8ed444-6269-47c9-baac-df36933d3243.jpg)

**Comment by jas14** [comment] 2022-09-11 20:45
Duplicate of #1793.

@Matzthias , this unfortunately has been a common report since 7.16.0. Please comment on #1793 with more information (at least OS and device make & model), that will be very helpful. Thanks

**Closed by jas14** 2022-09-11 20:45 UTC
Labels: bug

**Comment by Matzthias** [comment] 2022-09-12 10:03
Android 8.0. I think it's an huawei p8 lite (WAS-TL10)
