### ISSUE TITLE
My game with Casper419 cheated by bug

### ISSUE THREAD

**Issue by wallpapper** [lichess-org/lichobile#2148] opened 2022-07-19 08:02 UTC
When I played the game with Casper419 my Knight was after my move from d7 to f8 immediatelly moved to d8. I would like to know how this is possible? I lost this game because of terrible coordinatin of my pieces... 
With best regards
George W.

**Comment by jas14** [comment] 2022-08-08 22:00
@wallpapper , your report doesn't follow the template, so we don't have a lot to work off here. This seems like a duplicate of #2125, so I'm closing it as such. If that issue description matches what you're seeing, please give it a thumbs-up to indicate you're also affected.

**Closed by jas14** 2022-08-08 22:00 UTC
